import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/header/Navbar";
import { QueryClientProvider } from '@tanstack/react-query';
import queryClient from "@/queryClient";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ 
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <QueryClientProvider client={queryClient}>
        <body className="">
            <Navbar /> 
            <main>{children}</main> {/* Main content area */}
            <ToastContainer/>        
        </body>
      </QueryClientProvider>
    </html>
  );
}
